cephadm compatibility
Add `ceph` executable printing this component version, required by cephadm

cephadm `command_pull()`, during pulling the container images, calls to [command_inspect_image](https://github.com/ceph/ceph/blob/fd62a8dfcb345fabed3eea6b3a461f1ca848a239/src/cephadm/cephadm.py#L4995-L5011) which execs in container ["ceph --version"](https://github.com/ceph/ceph/blob/fd62a8dfcb345fabed3eea6b3a461f1ca848a239/src/cephadm/cephadm.py#L5007)

see [here](https://github.com/ceph/ceph/blob/fd62a8dfcb345fabed3eea6b3a461f1ca848a239/src/cephadm/cephadm.py#L5007):

```python
    ver = CephContainer(ctx, ctx.image, 'ceph', ['--version']).run().strip()
```

Example error:
```shell
RuntimeError: Failed command: /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint ceph --init -e CONTAINER_IMAGE=quay.io/ceph/nvmeof:0.0.1 -e NODE_NAME=centos9 quay.io/ceph/nvmeof:0.0.1 --version: ERROR (catatonit:2): failed to exec pid1: No such file or directory
```

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>