control/cli.py: handle connection refused
Example mtls test: https://github.com/ceph/ceph-nvmeof/actions/runs/11421827968/job/31779220634

CLI_TLS_ARGS --server-cert /etc/ceph/server.crt --client-key /etc/ceph/client.key --client-cert /etc/ceph/client.crt
Container 1 87745defee53 is now running.
Container 1 87745defee53 192.168.13.3 subsystems:
Enable server auth since both --client-key and --client-cert are provided
error: get_subsystems failed: code=StatusCode.UNAVAILABLE message=failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.13.3:5500: Failed to connect to remote host: Connection refused
usage: python3 -m control.cli [-h] [--format {text,json,yaml,plain,python}]
                              [--output {log,stdio}]
                              [--log-level {debug,DEBUG,info,INFO,warning,WARNING,error,ERROR,critical,CRITICAL}]
                              [--server-address SERVER_ADDRESS]
                              [--server-port SERVER_PORT]
                              [--client-key CLIENT_KEY]
                              [--client-cert CLIENT_CERT]
                              [--server-cert SERVER_CERT] [--verbose]
                              {version,gw,spdk_log_level,subsystem,listener,host,connection,namespace,ns,get_subsystems}
                              ...

++ docker compose run --rm nvmeof-cli --server-address 192.168.13.3 --server-port 5500 --server-cert /etc/ceph/server.crt --client-key /etc/ceph/client.key --client-cert /etc/ceph/client.crt subsystem add --subsystem nqn.2016-06.io.spdk:cnode1 --no-group-append
Enable server auth since both --client-key and --client-cert are provided
Failure adding subsystem nqn.2016-06.io.spdk:cnode1:
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.13.3:5500: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.13.3:5500: Failed to connect to remote host: Connection refused {created_time:"2024-10-20T00:27:59.51879366+00:00", grpc_status:14}"

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>